name: dev-deployment

on: push

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  AWS_IAM_ROLE: arn:aws:iam::237110372189:role/GitHubAction-AssumeRoleWithAction

jobs:
  test-aws-access:
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v3
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ env.AWS_IAM_ROLE }}
          role-session-name: assumerolesession
          aws-region: ${{ env.AWS_REGION }}
      - name: Get caller identity
        run: aws sts get-caller-identity
      - name: Login to Amazon ECR Public
        id: login-ecr-public
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'
          registry-type: public

      - name: Build, tag, and push docker image to Amazon ECR Public
        working-directory: ./app
        env:
          REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
          REGISTRY_ALIAS: t6y6o8s3
          REPOSITORY: sample-app
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $REPOSITORY:$IMAGE_TAG .
          docker tag $REPOSITORY:$IMAGE_TAG $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
          docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
  deploy:
    defaults:
      run:
        working-directory: terraform
    needs:
      - test-aws-access
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1

      - uses: hashicorp/setup-terraform@v2

      - run: terraform init

      - id: plan
        run: terraform plan -no-color
